# Generated by Django 5.1.5 on 2025-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
